// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_DL-RFshy9m6l9d5E18rTTq63NJJhjw',
    appId: '1:222083994414:web:ff4dc90a2f432f8758a0bf',
    messagingSenderId: '222083994414',
    projectId: 'lina-project-c7424',
    authDomain: 'lina-project-c7424.firebaseapp.com',
    storageBucket: 'lina-project-c7424.appspot.com',
    measurementId: 'G-9KD97NZTNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0FLQsGq99t3Lb4LlHzRC6pqt_e0rV1Y0',
    appId: '1:222083994414:android:5771c5c9113cda4f58a0bf',
    messagingSenderId: '222083994414',
    projectId: 'lina-project-c7424',
    storageBucket: 'lina-project-c7424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhO1cYFcXxHzReNKd0wfd7IKaPRfjRSp8',
    appId: '1:222083994414:ios:3cd36bf827baa32258a0bf',
    messagingSenderId: '222083994414',
    projectId: 'lina-project-c7424',
    storageBucket: 'lina-project-c7424.appspot.com',
    iosBundleId: 'com.example.vitafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhO1cYFcXxHzReNKd0wfd7IKaPRfjRSp8',
    appId: '1:222083994414:ios:24897400e533310c58a0bf',
    messagingSenderId: '222083994414',
    projectId: 'lina-project-c7424',
    storageBucket: 'lina-project-c7424.appspot.com',
    iosBundleId: 'com.example.vitafit.RunnerTests',
  );
}
